Aula8_aspNET/Consultorio/Consultorio/Models/Monstro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Consultorio.Models
{
    public class Monstro
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Ataque { get; set; }
    }
}

Aula8_aspNET/Consultorio/Consultorio/Models/Paciente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Consultorio.Models
{
    public class Paciente
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public DateTime Nascimento { get; set; }
    }
}

Aula8_aspNET/Consultorio/Consultorio/Controllers/MonstroController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Consultorio.Models;

namespace Consultorio.Controllers
{
    public class MonstroController : Controller
    {
        public List<Monstro> listaMonstros = new List<Monstro>();
        public IActionResult Index()
        {
            listaMonstros.Add(new Monstro { Id = 1, Nome = "BestaFera" });
            listaMonstros.Add(new Monstro { Id = 2, Nome = "Godzilla" });
            ViewBag.monstros = listaMonstros;
            return View();
        }
    }
}

Aula8_aspNET/Consultorio/Consultorio/Controllers/PacienteController.cs
using Consultorio.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Consultorio.Controllers
{
    public class PacienteController : Controller
    {
        public List<Paciente> pacientes = new List<Paciente>();
        public IActionResult Index()
        {
            pacientes.Add(new Paciente { Id = 1, Nome = "Mauro Rodriguez" });
            pacientes.Add(new Paciente { Id = 2, Nome = "Blanca Evangelista" });
            ViewBag.pacientes = pacientes;
            return View();
        }
    }
}

Aula8_aspNET/Consultorio/Consultorio/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Aula8_aspNET/Consultorio/Consultorio/Views/Home/Info.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


Essa é a página de informações.

Aula8_aspNET/Consultorio/Consultorio/Views/Monstro/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Nome</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Monstro m in ViewBag.monstros)
        {
            <tr>
                <th scope="row">@m.Id</th>
                <td>@m.Nome</td>
            </tr>
        }
    </tbody>
</table>

Aula8_aspNET/Consultorio/Consultorio/Views/Paciente/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Nome</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Paciente p in ViewBag.pacientes)
            {
                <tr>
                    <th scope="row">@p.Id</th>
                    <td>@p.Nome</td>
                </tr>
            }
    </tbody>
</table>

Aula8_aspNET/Consultorio/Consultorio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Consultorio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Consultorio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Info">Informações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paciente" asp-action="Index">Pacientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Monstro" asp-action="Index">Lista de Monstros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Consultorio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>